name: 🐛 Bug Report
description: Report a problem with openwrt-captive-monitor
title: "[Bug]: "
labels: ["bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to file a bug report! Please fill out the form below to help us reproduce and fix the issue.

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug in one or two sentences...
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Information about your setup that helps us reproduce the issue.
      value: |
        - Router model / SoC:
        - OpenWrt version:
        - Package version:
        - Runtime mode (`monitor` or `oneshot`):
        - Anything else that might be relevant:
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Step-by-step instructions to reproduce the behavior.
      placeholder: |
        1. Run '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: Tell us what you expected to happen.
      placeholder: Describe what should have happened...
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: Tell us what actually happened. Include logs if possible.
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs, traces, and configuration
      description: Paste relevant log extracts or attach files. Redact secrets before sharing.
      render: shell

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other information, screenshots, or context about the problem here.

  - type: checkboxes
    id: terms
    attributes:
      label: Acceptance
      description: By submitting this issue, you agree to the following:
      options:
        - label: I have searched existing issues for similar reports
          required: true
        - label: I have provided enough information to reproduce the issue
          required: true
        - label: I have removed any sensitive information from logs and configuration
          required: true