name: 📚 Documentation Issue
description: Report issues or suggest improvements to documentation
title: "[Docs]: "
labels: ["documentation"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation! Good documentation is crucial for making openwrt-captive-monitor accessible to everyone.

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation type
      description: What type of documentation issue are you reporting?
      options:
        - Incorrect information
        - Missing information
        - Unclear or confusing content
        - Outdated content
        - Broken links
        - Formatting issues
        - New documentation suggestion
        - Translation/language issue
    validations:
      required: true

  - type: dropdown
    id: doc-location
    attributes:
      label: Documentation location
      description: Where is the affected documentation?
      options:
        - README.md
        - docs/contributing/CONTRIBUTING.md
        - docs/release/CHANGELOG.md
        - docs/ directory (specify below)
        - Inline code comments
        - GitHub templates
        - Other (specify below)
    validations:
      required: true

  - type: textarea
    id: location-details
    attributes:
      label: Specific location
      description: Please provide the specific file path, section, or line number if applicable.
      placeholder: e.g., docs/configuration/advanced.md, section "DNS Configuration", or line 45 of README.md

  - type: textarea
    id: issue-description
    attributes:
      label: Issue description
      description: Please describe the documentation issue in detail.
      placeholder: What's wrong with the documentation? What needs to be improved?
    validations:
      required: true

  - type: textarea
    id: suggested-change
    attributes:
      label: Suggested change
      description: If you have a specific improvement in mind, please describe it here.
      placeholder: How would you like to see this documentation improved?

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Any other information that would help us understand and address the documentation issue.

  - type: checkboxes
    id: terms
    attributes:
      label: Acceptance
      description: By submitting this documentation issue, you agree to the following:
      options:
        - label: I have checked that this issue hasn't been reported before
          required: true
        - label: I understand that documentation contributions are welcome
          required: true