#!/bin/bash
set -e

# Version from Makefile or argument
VERSION="2026.01.16.5-1"
BUILD_DIR="build_tmp"
OUTPUT_DIR="build_ipk"
PACKAGE_NAME="openwrt-captive-monitor_${VERSION}_all.ipk"

mkdir -p "$OUTPUT_DIR"

# Ensure we are in the project root
if [ ! -d "package/openwrt-captive-monitor" ]; then
    echo "Error: Must be run from project root"
    exit 1
fi

# Prepare build directory
rm -rf "$BUILD_DIR"
mkdir -p "$BUILD_DIR/control" "$BUILD_DIR/data/usr/sbin"

# Copy files
cp package/openwrt-captive-monitor/files/usr/sbin/auth_conn4.sh "$BUILD_DIR/data/usr/sbin/"
# Note: control files are usually generated by OpenWrt build system. 
# For standalone build, we need to create them or copy from a source.
# Assuming we have them in files/control/ (which we don't in repo, but I generated them in previous steps)
# Let's generate them on the fly for consistency
cat <<EOF > "$BUILD_DIR/control/control"
Package: openwrt-captive-monitor
Version: $VERSION
Depends: libc, curl, shadow-utils
Source: package/openwrt-captive-monitor
Section: net
Architecture: all
Maintainer: OpenWrt Developers
Description:  Captive Portal Monitor
EOF

cat <<EOF > "$BUILD_DIR/control/postinst"
#!/bin/sh
[ -n "\$IPKG_INSTROOT" ] && exit 0
sed -i '\#/usr/sbin/auth_conn4.sh#d' /etc/crontabs/root 2>/dev/null
echo "*/1 * * * * /usr/sbin/auth_conn4.sh" >> /etc/crontabs/root
/etc/init.d/cron restart
exit 0
EOF

chmod 755 "$BUILD_DIR/control/postinst"
chmod 755 "$BUILD_DIR/data/usr/sbin/auth_conn4.sh"

# Fix line endings (crucial for WSL/Windows)
dos2unix "$BUILD_DIR/control/control" "$BUILD_DIR/control/postinst" "$BUILD_DIR/data/usr/sbin/auth_conn4.sh" 2>/dev/null || true

# Build inner archives
cd "$BUILD_DIR"
tar --numeric-owner --group=0 --owner=0 -czf control.tar.gz -C control .
tar --numeric-owner --group=0 --owner=0 -czf data.tar.gz -C data .
echo "2.0" > debian-binary

# Build outer archive (IPK)
# Note: Standard IPK is AR archive. However, some opkg versions accept tar.gz.
# We use tar.gz here as it proved to work on the target device where ar failed.
tar -czf "../$OUTPUT_DIR/$PACKAGE_NAME" debian-binary control.tar.gz data.tar.gz

cd ..
echo "Built $OUTPUT_DIR/$PACKAGE_NAME"
